# Generated by Django 6.0.1 on 2026-02-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='news_images/'),
        ),
    ]
