# Generated by Django 6.0.1 on 2026-02-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_news_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='contact_images/'),
        ),
    ]
